apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: searxng
  namespace: home-search
spec:
  hostnames:
  - search.yuchanns.xyz
  parentRefs:
  - name: cilium-gateway
    namespace: network
  rules:
  - matches:
    - path:
        type: PathPrefix
        value: /
    backendRefs:
    - name: searxng
      port: 8080

