apiVersion: apps/v1
kind: Deployment
metadata:
  name: emby
  namespace: home-theater
spec:
  replicas: 1
  selector:
    matchLabels:
      app: emby
  template:
    metadata:
      labels:
        app: emby
    spec:
      hostname: emby
      containers:
      - image: ghcr.io/linuxserver/emby:4.8.5
        imagePullPolicy: IfNotPresent
        name: emby
        ports:
        - containerPort: 8096
          protocol: TCP
        env:
        - name: PUID
          value: "1000"
        - name: GUID
          value: "1000"
        - name: TZ
          value: Asia/Shanghai
        volumeMounts:
        - mountPath: /config
          name: home-theater
          subPath: emby-config
        - mountPath: /media
          name: home-theater
          subPath: media
        - mountPath: /alist
          name: alist-dav
      volumes:
      - name: home-theater
        persistentVolumeClaim:
          claimName: home-theater
      - name: alist-dav
        persistentVolumeClaim:
          claimName: alist-dav
---
apiVersion: v1
kind: Service
metadata:
  name: emby
  namespace: home-theater
  labels:
    app: emby
spec:
  ports:
  - port: 8096
    name: http
  selector:
    app: emby
---
apiVersion: v1
kind: Service
metadata:
  name: emby-nodeport
  namespace: home-theater
  labels:
    app: emby
spec:
  ports:
  - port: 8096
    nodePort: 31096
    name: http
  type: NodePort
  selector:
    app: emby
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: emby
  namespace: home-theater
spec:
  hostnames:
  - emby.yuchanns.xyz
  parentRefs:
  - name: cilium-gateway
    namespace: network
  rules:
  - matches:
    - path:
        type: PathPrefix
        value: /
    backendRefs:
    - name: emby
      port: 8096

