apiVersion: apps/v1
kind: Deployment
metadata:
  name: emby
  namespace: home-theater
spec:
  replicas: 1
  selector:
    matchLabels:
      app: emby
  template:
    metadata:
      labels:
        app: emby
    spec:
      containers:
      - image: lscr.io/linuxserver/emby:4.7.11
        imagePullPolicy: IfNotPresent
        name: emby
        ports:
        - containerPort: 8096
          protocol: TCP
        env:
        - name: PUID
          value: "1000"
        - name: GUID
          value: "1000"
        - name: TZ
          value: Asia/Shanghai
        volumeMounts:
        - mountPath: /config
          name: home-theater
          subPath: emby-config
        - mountPath: /media
          name: home-theater
          subPath: media
      volumes:
      - name: home-theater
        persistentVolumeClaim:
          claimName: home-theater
---
apiVersion: v1
kind: Service
metadata:
  name: emby
  namespace: home-theater
  labels:
    app: emby
spec:
  ports:
  - port: 8096
    name: http
  selector:
    app: emby
---
apiVersion: v1
kind: Service
metadata:
  name: emby-nodeport
  namespace: home-theater
  labels:
    app: emby
spec:
  ports:
  - port: 8096
    nodePort: 31096
    name: http
  type: NodePort
  selector:
    app: emby
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: emby-insecure
  namespace: home-theater
spec:
  entryPoints:
    - web
  routes:
    - match: Host(`emby.yuchanns.xyz`)
      kind: Rule
      services:
        - name: emby
          port: 8096

