apiVersion: apps/v1
kind: Deployment
metadata:
  name: emby
  namespace: home-theater
spec:
  replicas: 1
  selector:
    matchLabels:
      app: emby
  template:
    metadata:
      labels:
        app: emby
    spec:
      containers:
      - image: lscr.io/linuxserver/emby:4.7.11
        imagePullPolicy: IfNotPresent
        name: emby
        ports:
        - containerPort: 8096
          protocol: TCP
        env:
        - name: TZ
          value: Asia/Shanghai
        volumeMounts:
        - mountPath: /config
          name: home-theater
          subPath: emby-config
        - mountPath: /movies
          name: home-theater
          subPath: emby-media
        - mountPath: /tvshows
          name: home-theater
          subPath: emby-tvshows
      volumes:
      - name: home-theater
        persistentVolumeClaim:
          claimName: home-theater
---
apiVersion: v1
kind: Service
metadata:
  name: emby
  namespace: home-theater
  labels:
    app: emby
spec:
  ports:
  - port: 8096
    name: http
  selector:
    app: emby

