apiVersion: apps/v1
kind: Deployment
metadata:
  name: jackett
  namespace: home-theater
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jackett
  template:
    metadata:
      labels:
        app: jackett
    spec:
      hostname: jackett
      containers:
      - image: ghcr.io/linuxserver/jackett:0.21.2536
        imagePullPolicy: IfNotPresent
        name: jackett
        env:
        - name: TZ
          value: Asia/Shanghai
        - name: AUTO_UPDATE
          value: "false"
        ports:
        - containerPort: 9117
          protocol: TCP
        volumeMounts:
        - mountPath: /config
          name: home-theater
          subPath: jackett-config
      volumes:
      - name: home-theater
        persistentVolumeClaim:
          claimName: home-theater
---
apiVersion: v1
kind: Service
metadata:
  name: jackett
  namespace: home-theater
  labels:
    app: jackett
spec:
  ports:
  - port: 9117
    name: webui
  selector:
    app: jackett
---
apiVersion: v1
kind: Service
metadata:
  name: jackett-nodeport
  namespace: home-theater
  labels:
    app: jackett
spec:
  ports:
  - port: 9117
    nodePort: 31117
    name: webui
  type: NodePort
  selector:
    app: jackett

