apiVersion: apps/v1
kind: Deployment
metadata:
  name: nas-tools
  namespace: home-theater
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nas-tools
  template:
    metadata:
      labels:
        app: nas-tools
    spec:
      containers:
      - image: diluka/nas-tools:2.9.1
        imagePullPolicy: IfNotPresent
        name: nas-tools
        ports:
        - containerPort: 3000
          name: webui
          protocol: TCP
        volumeMounts:
        - mountPath: /config
          name: home-theater
          subPath: nastools-config
        - mountPath: /media
          name: home-theater
          subPath: media
        env:
        - name: NASTOOL_AUTO_UPDATE
          value: "false"
        - name: NASTOOL_CN_UPDATE
          value: "false"
      volumes:
      - name: home-theater
        persistentVolumeClaim:
          claimName: home-theater
---
apiVersion: v1
kind: Service
metadata:
  name: nas-tools
  namespace: home-theater
  labels:
    app: nas-tools
spec:
  ports:
  - port: 3000
    name: http
  selector:
    app: nas-tools
---
apiVersion: v1
kind: Service
metadata:
  name: nas-tools-nodport
  namespace: home-theater
  labels:
    app: nas-tools
spec:
  ports:
  - port: 3000
    name: http
    nodePort: 31300
  type: NodePort
  selector:
    app: nas-tools

