apiVersion: v1
kind: ConfigMap
metadata:
  name: rclone
  namespace: home-theater
data:
  rclone.conf: |
    [NASTOOL]
    type = webdav
    url = http://alist.home-theater:5244/dav
    vendor = other
    user = yuchanns
    pass = cmOjdE7hjuWuJHrDun5d7D9TMiuFQFU_r4uU0f_lstzn4v8
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nas-tools
  namespace: home-theater
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nas-tools
  template:
    metadata:
      labels:
        app: nas-tools
    spec:
      hostname: nas-tools
      containers:
      - image: diluka/nas-tools:2.9.1
        imagePullPolicy: IfNotPresent
        name: nas-tools
        ports:
        - containerPort: 3000
          name: webui
          protocol: TCP
        volumeMounts:
        - mountPath: /config
          name: home-theater
          subPath: nastools-config
        - mountPath: /media/download
          name: home-theater
          subPath: media
        - name: config
          mountPath: /root/.config/rclone
          readOnly: true
        env:
        - name: NASTOOL_AUTO_UPDATE
          value: "false"
        - name: NASTOOL_CN_UPDATE
          value: "false"
        resources:
          limits:
            nextflow.io/fuse: 1
        securityContext:
          privileged: true
      volumes:
      - name: home-theater
        persistentVolumeClaim:
          claimName: home-theater
      - name: config
        configMap:
          name: rclone
          items:
          - key: rclone.conf
            path: rclone.conf
---
apiVersion: v1
kind: Service
metadata:
  name: nas-tools
  namespace: home-theater
  labels:
    app: nas-tools
spec:
  ports:
  - port: 3000
    name: http
  selector:
    app: nas-tools
---
apiVersion: v1
kind: Service
metadata:
  name: nas-tools-nodport
  namespace: home-theater
  labels:
    app: nas-tools
spec:
  ports:
  - port: 3000
    name: http
    nodePort: 31300
  type: NodePort
  selector:
    app: nas-tools
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: nas-tools
  namespace: home-theater
spec:
  hostnames:
  - nas-tools.yuchanns.xyz
  parentRefs:
  - name: cilium-gateway
    namespace: network
  rules:
  - matches:
    - path:
        type: PathPrefix
        value: /
    backendRefs:
    - name: nas-tools
      port: 3000

