kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: home-theater
  namespace: home-theater
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1024Gi
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: home-theater-ext
  namespace: home-theater
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 4096Gi
  storageClassName: local-path-ext

