apiVersion: apps/v1
kind: Deployment
metadata:
  name: subfinder
  namespace: home-theater
spec:
  replicas: 1
  selector:
    matchLabels:
      app: subfinder
  template:
    metadata:
      labels:
        app: subfinder
    spec:
      hostname: subfinder
      containers:
      - image: allanpk716/chinesesubfinder:v0.55.2
        imagePullPolicy: IfNotPresent
        name: subfinder
        ports:
        - containerPort: 19035
          protocol: TCP
        - containerPort: 19037
          protocol: TCP
        env:
        - name: PUID
          value: "1000"
        - name: GUID
          value: "1000"
        - name: PERMS
          value: "false"
        - name: UMASK
          value: "022"
        - name: TZ
          value: Asia/Shanghai
        volumeMounts:
        - mountPath: /config
          name: home-theater
          subPath: subfinder-config
        - mountPath: /root/.cache/rod/browser
          name: home-theater
          subPath: subfinder-browser
        - mountPath: /media
          name: home-theater
          subPath: media
        - mountPath: /alist
          name: alist-dav
      volumes:
      - name: home-theater
        persistentVolumeClaim:
          claimName: home-theater
      - name: alist-dav
        persistentVolumeClaim:
          claimName: alist-dav
---
apiVersion: v1
kind: Service
metadata:
  name: subfinder
  namespace: home-theater
  labels:
    app: subfinder
spec:
  ports:
  - port: 19035
    name: http
  selector:
    app: subfinder
---
apiVersion: v1
kind: Service
metadata:
  name: subfinder-nodeport
  namespace: home-theater
  labels:
    app: subfinder
spec:
  ports:
  - port: 19035
    nodePort: 31090
    name: http
  type: NodePort
  selector:
    app: subfinder
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: subfinder
  namespace: home-theater
spec:
  hostnames:
  - subfinder.yuchanns.xyz
  parentRefs:
  - name: cilium-gateway
    namespace: network
  rules:
  - matches:
    - path:
        type: PathPrefix
        value: /
    backendRefs:
    - name: subfinder
      port: 19035
