apiVersion: apps/v1
kind: Deployment
metadata:
  name: windows
  namespace: home-os
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: windows
  template:
    metadata:
      labels:
        app: windows
    spec:
      containers:
        - image: dockurr/windows:latest
          imagePullPolicy: IfNotPresent
          name: windows
          ports:
            - containerPort: 8006
              name: vnc
              protocol: TCP
            - containerPort: 3389
              name: rdp-tcp
              protocol: TCP
            - containerPort: 3389
              name: rdp-udp
              protocol: UDP
          env:
            - name: VERSION
              value: win11
            - name: RAM_SIZE
              value: 8G
            - name: CPU_CORES
              value: "2"
            - name: DISK_SIZE
              value: 256G
          securityContext:
            allowPrivilegeEscalation: true
            capabilities:
              add:
                - NET_ADMIN
                - NET_BIND_SERVICE
                - NET_BROADCAST
                - NET_RAW
                - AUDIT_CONTROL
                - FOWNER
                - MKNOD
                - SETGID
                - SYS_CHROOT
                - AUDIT_WRITE
                - DAC_OVERRIDE
                - FSETID
                - KILL
                - SETPCAP
                - SETFCAP
                - SETUID
            privileged: true
            readOnlyRootFilesystem: false
            runAsNonRoot: false
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
            - mountPath: /storage
              name: home-os
              subPath: win11
            - mountPath: /dev/kvm
              name: kvm
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
        - name: home-os
          persistentVolumeClaim:
            claimName: home-os
        - hostPath:
            path: /dev/kvm
            type: CharDevice
          name: kvm
---
apiVersion: v1
kind: Service
metadata:
  name: windows
  namespace: home-os
  labels:
    app: windows
spec:
  ports:
  - port: 8006
    name: vnc
  selector:
    app: windows
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: windows
  namespace: home-os
spec:
  hostnames:
  - vnc.yuchanns.xyz
  parentRefs:
  - name: cilium-gateway
    namespace: network
  rules:
  - matches:
    - path:
        type: PathPrefix
        value: /
    backendRefs:
    - name: windows
      port: 8006
