apiVersion: apps/v1
kind: Deployment
metadata:
  name: warp
  namespace: home-proxy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: warp
  template:
    metadata:
      labels:
        app: warp
    spec:
      hostname: warp
      containers:
      - image: yuchanns/warp-clash-api:0744926
        imagePullPolicy: IfNotPresent
        name: warp
        env:
        - name: SECRET_KEY
          value: nyp9xpy!cvq1CWN@cth
        ports:
        - containerPort: 3000
          name: webui
          protocol: TCP
        volumeMounts:
        - mountPath: /app/account
          name: home-proxy
          subPath: warp_account
      volumes:
      - name: home-proxy
        persistentVolumeClaim:
          claimName: home-proxy
---
apiVersion: v1
kind: Service
metadata:
  name: warp
  namespace: home-proxy
  labels:
    app: warp
spec:
  ports:
  - port: 3000
    name: http
  selector:
    app: warp
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: warp-insecure
  namespace: home-proxy
spec:
  entryPoints:
    - web
  routes:
    - match: Host(`warp.yuchanns.xyz`)
      kind: Rule
      services:
        - name: warp
          port: 3000

